package com.bawei.gekaixuan.Greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bawei.gekaixuan.Greendao.shopcartdaobean;

import com.bawei.gekaixuan.Greendao.shopcartdaobeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shopcartdaobeanDaoConfig;

    private final shopcartdaobeanDao shopcartdaobeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shopcartdaobeanDaoConfig = daoConfigMap.get(shopcartdaobeanDao.class).clone();
        shopcartdaobeanDaoConfig.initIdentityScope(type);

        shopcartdaobeanDao = new shopcartdaobeanDao(shopcartdaobeanDaoConfig, this);

        registerDao(shopcartdaobean.class, shopcartdaobeanDao);
    }
    
    public void clear() {
        shopcartdaobeanDaoConfig.clearIdentityScope();
    }

    public shopcartdaobeanDao getShopcartdaobeanDao() {
        return shopcartdaobeanDao;
    }

}
